#!/bin/bash
#
# dummy submitscript for running embarassingly parallell opencmiss jobs
# iterating over parameter sets. All parameters are kept in a tab-separated 
# text file with one line per parameter set. The parameters_dummy file 
# contains three parameter set with four parameter

# Job parameters
export parfile="Parameters.csv"    # File with parameter sets


# Extract number of parameter sets
export Npars=$(wc -l $parfile | awk '{print $1}')

# Loop over parameter sets and submit jobs
for TASK_ID in $(seq 1 $Npars); 
do  
    echo -ne "* Submitting job "$TASK_ID" ... "
    # TODO: submit job to queue system
    ./bin/x86_64-linux/mpich2/gnu/QuadraticEllipsoidCostaReadInExample-debug $(cat $parfile | sed $TASK_ID'q;d') > dummy.$TASK_ID.log
done
