PROGRAM FINITEELASTICITYEXAMPLE

  USE BASE_ROUTINES
  USE BASIS_ROUTINES
  USE CMISS
  USE CMISS_MPI
  USE COMP_ENVIRONMENT
  USE CONSTANTS
  USE COORDINATE_ROUTINES
  USE DISTRIBUTED_MATRIX_VECTOR
  USE DOMAIN_MAPPINGS
  USE EQUATIONS_SET_CONSTANTS
  USE EQUATIONS_SET_ROUTINES
  USE FIELD_ROUTINES
  USE FIELD_IO_ROUTINES
  USE INPUT_OUTPUT
  USE ISO_VARYING_STRING
  USE KINDS
  USE LISTS
  USE MESH_ROUTINES
  USE MPI
  USE PROBLEM_CONSTANTS
  USE PROBLEM_ROUTINES
  USE REGION_ROUTINES
  USE SOLVER_ROUTINES
  USE TIMER
  USE TYPES


  !Program variables

  INTEGER(INTG) :: NUMBER_OF_DOMAINS  
  INTEGER(INTG) :: NUMBER_COMPUTATIONAL_NODES
  INTEGER(INTG) :: MY_COMPUTATIONAL_NODE_NUMBER
  INTEGER(INTG) :: MPI_IERROR

  INTEGER(INTG) :: first_global_dof,first_local_dof,first_local_rank,last_global_dof
  INTEGER(INTG) :: last_local_dof,last_local_rank,rank_idx
  INTEGER(INTG) :: np,np_idx,npt,ne,ne_idx,net
  INTEGER(INTG) :: EQUATIONS_SET_INDEX
  TYPE(DOMAIN_MAPPING_TYPE), POINTER :: DEPENDENT_DOF_MAPPING

  TYPE(COORDINATE_SYSTEM_TYPE), POINTER :: globalcoordinate
  TYPE(REGION_TYPE), POINTER :: region1
  TYPE(BASIS_TYPE), POINTER :: basis1
  TYPE(MESH_TYPE), POINTER :: mesh1
  TYPE(DECOMPOSITION_TYPE), POINTER :: decompositon
  TYPE(FIELD_TYPE), POINTER :: undeffield,fibrefield,materialfield,deffield,boundaryfield,GEOMETRIC_FIELD  
  TYPE(EQUATIONS_SET_TYPE), POINTER :: equation
  TYPE(PROBLEM_TYPE), POINTER :: problem
  TYPE(SOLVER_TYPE), POINTER :: solver
  
  LOGICAL :: EXPORT_FIELD,IMPORT_FIELD
  TYPE(VARYING_STRING) :: FILE,METHOD


  !Generic CMISS variables  
  INTEGER(INTG) :: ERR
  TYPE(VARYING_STRING) :: ERROR

  
  !Intialise cmiss
  CALL CMISS_INITIALISE(ERR,ERROR,*999)
  
  NUMBER_OF_DOMAINS=1
    
  !Get the number of computational nodes
  NUMBER_COMPUTATIONAL_NODES=COMPUTATIONAL_NODES_NUMBER_GET(ERR,ERROR)
  IF(ERR/=0) GOTO 999
  !Get my computational node number
  MY_COMPUTATIONAL_NODE_NUMBER=COMPUTATIONAL_NODE_NUMBER_GET(ERR,ERROR)
  IF(ERR/=0) GOTO 999
  
  !Broadcast the number of elements in the X & Y directions and the number of partitions to the other computational nodes
  CALL MPI_BCAST(1,1,MPI_INTEGER,0,MPI_COMM_WORLD,MPI_IERROR)
  CALL MPI_ERROR_CHECK("MPI_BCAST",MPI_IERROR,ERR,ERROR,*999)
  CALL MPI_BCAST(1,1,MPI_INTEGER,0,MPI_COMM_WORLD,MPI_IERROR)
  CALL MPI_ERROR_CHECK("MPI_BCAST",MPI_IERROR,ERR,ERROR,*999)
  CALL MPI_BCAST(1,1,MPI_INTEGER,0,MPI_COMM_WORLD,MPI_IERROR)
  CALL MPI_ERROR_CHECK("MPI_BCAST",MPI_IERROR,ERR,ERROR,*999)
  CALL MPI_BCAST(NUMBER_OF_DOMAINS,1,MPI_INTEGER,0,MPI_COMM_WORLD,MPI_IERROR)
  CALL MPI_ERROR_CHECK("MPI_BCAST",MPI_IERROR,ERR,ERROR,*999)
  CALL WRITE_STRING(GENERAL_OUTPUT_TYPE,"COMPUTATIONAL ENVIRONMENT:",ERR,ERROR,*999)
  CALL WRITE_STRING_VALUE(GENERAL_OUTPUT_TYPE,  &
    &"  Total number of computaional nodes = ",NUMBER_COMPUTATIONAL_NODES, &
    & ERR,ERROR,*999)
  CALL WRITE_STRING_VALUE(GENERAL_OUTPUT_TYPE,"  My computational node number = ", &
    & MY_COMPUTATIONAL_NODE_NUMBER,ERR,ERROR,*999)


!************************************************************************************
  !create a 3D RC coordinate system 
  CALL COORDINATE_SYSTEM_CREATE_START(1,globalcoordinate,ERR,ERROR,*999) ! default is 3D RC coordinate system
  CALL COORDINATE_SYSTEM_CREATE_FINISH(globalcoordinate,ERR,ERROR,*999)

  !create a region
  CALL REGION_CREATE_START(1,region1,ERR,ERROR,*999)  ! default is to assign CS already created                
  CALL REGION_CREATE_FINISH(region1,ERR,ERROR,*999)

  !define trilinear lagrange basis
  CALL BASIS_CREATE_START(1,basis1,ERR,ERROR,*999) ! default tri-linear Lagrange with 2 Gauss pts in each xi 
  CALL BASIS_CREATE_FINISH(basis1,ERR,ERROR,*999)

  !create a regular mesh    
  CALL MESH_CREATE_REGULAR(1,region1,(/0.0_DP,0.0_DP,0.0_DP/),(/1.0_DP,1.0_DP,1.0_DP/), &
    & (/1,1,1/),basis1,mesh1,ERR,ERROR,*999)

  !create a decomposition
  CALL DECOMPOSITION_CREATE_START(1,mesh1,decompositon,ERR,ERROR,*999)
  CALL DECOMPOSITION_TYPE_SET(decompositon,DECOMPOSITION_CALCULATED_TYPE,ERR,ERROR,*999)
  CALL DECOMPOSITION_NUMBER_OF_DOMAINS_SET(decompositon,NUMBER_OF_DOMAINS,ERR,ERROR,*999)
  CALL DECOMPOSITION_CREATE_FINISH(mesh1,decompositon,ERR,ERROR,*999)

!******
  !create a field on the region to put undeformed geometry
  CALL FIELD_CREATE_START(1,region1,undeffield,ERR,ERROR,*999)  
  CALL FIELD_TYPE_SET(1,region1,1,ERR,ERROR,*999)
  CALL FIELD_MESH_DECOMPOSITION_SET(undeffield,decompositon,ERR,ERROR,*999)
  CALL FIELD_CREATE_FINISH(region1,undeffield,ERR,ERROR,*999)
  CALL FIELD_GEOMETRIC_PARAMETERS_UPDATE_FROM_INITIAL_MESH(undeffield,ERR,ERROR,*999)
!******

!******
  !create a fibre field and attach it to the geometric field
  CALL FIELD_CREATE_START(2,region1,fibrefield,ERR,ERROR,*999)
  CALL FIELD_TYPE_SET(2,region1,2,ERR,ERROR,*999)
  CALL FIELD_MESH_DECOMPOSITION_SET(fibrefield,decompositon,ERR,ERROR,*999)        
  CALL FIELD_GEOMETRIC_FIELD_SET(2,region1,undeffield,ERR,ERROR,*999)   
  CALL FIELD_COMPONENT_INTERPOLATION_SET(2,1,1,region1,3,ERR,ERROR,*999)   
  CALL FIELD_COMPONENT_INTERPOLATION_SET(2,1,2,region1,3,ERR,ERROR,*999)   
  CALL FIELD_COMPONENT_INTERPOLATION_SET(2,1,3,region1,3,ERR,ERROR,*999)         
  CALL FIELD_CREATE_FINISH(region1,fibrefield,ERR,ERROR,*999) 
  
!******  

!****** 
  !create a material properties field and attach it to the geometric field
  CALL FIELD_CREATE_START(3,region1,materialfield,ERR,ERROR,*999) 
  CALL FIELD_TYPE_SET(3,region1,4,ERR,ERROR,*999)
  CALL FIELD_MESH_DECOMPOSITION_SET(materialfield,decompositon,ERR,ERROR,*999)   
  CALL FIELD_GEOMETRIC_FIELD_SET(3,region1,undeffield,ERR,ERROR,*999)     
  CALL FIELD_NUMBER_OF_COMPONENTS_SET(3,region1,2,ERR,ERROR,*999)
  CALL FIELD_COMPONENT_INTERPOLATION_SET(3,1,1,region1,3,ERR,ERROR,*999)   
  CALL FIELD_COMPONENT_INTERPOLATION_SET(3,1,2,region1,3,ERR,ERROR,*999)         
  CALL FIELD_CREATE_FINISH(region1,materialfield,ERR,ERROR,*999) 
  
  npt=mesh1%TOPOLOGY(1)%PTR%NODES%NUMBER_OF_NODES
  DO np_idx=1,npt,1
    np=mesh1%TOPOLOGY(1)%PTR%NODES%NODES(np_idx)%GLOBAL_NUMBER
    CALL FIELD_PARAMETER_SET_UPDATE_NODE(materialfield,1,1,np,1,1,2.0_DP,ERR,ERROR,*999)
    CALL FIELD_PARAMETER_SET_UPDATE_NODE(materialfield,1,1,np,2,1,3.0_DP,ERR,ERROR,*999)
  ENDDO
!******

!******
  !create a field for boundary conditions and attach it to the geometric field
  CALL FIELD_CREATE_START(4,region1,boundaryfield,ERR,ERROR,*999)
  CALL FIELD_TYPE_SET(4,region1,3,ERR,ERROR,*999) 
  CALL FIELD_MESH_DECOMPOSITION_SET(boundaryfield,decompositon,ERR,ERROR,*999)  
  CALL FIELD_GEOMETRIC_FIELD_SET(4,region1,undeffield,ERR,ERROR,*999)  
  CALL FIELD_NUMBER_OF_COMPONENTS_SET(4,region1,6,ERR,ERROR,*999)
  CALL FIELD_CREATE_FINISH(region1,boundaryfield,ERR,ERROR,*999)  
  DO np_idx=2,8,2
    CALL FIELD_PARAMETER_SET_UPDATE_NODE(boundaryfield,1,1,np_idx,1,1,1.0_DP,ERR,ERROR,*999)   
    CALL FIELD_PARAMETER_SET_UPDATE_NODE(boundaryfield,1,1,np_idx,2,1,0.0_DP,ERR,ERROR,*999)
    CALL FIELD_PARAMETER_SET_UPDATE_NODE(boundaryfield,1,1,np_idx,3,1,0.0_DP,ERR,ERROR,*999)  
    CALL FIELD_PARAMETER_SET_UPDATE_NODE(boundaryfield,1,1,np_idx,4,1,0.0_DP,ERR,ERROR,*999) 
    CALL FIELD_PARAMETER_SET_UPDATE_NODE(boundaryfield,1,1,np_idx,5,1,0.0_DP,ERR,ERROR,*999) 
    CALL FIELD_PARAMETER_SET_UPDATE_NODE(boundaryfield,1,1,np_idx,6,1,0.0_DP,ERR,ERROR,*999)           
  ENDDO
  DO np_idx=1,7,2
    CALL FIELD_PARAMETER_SET_UPDATE_NODE(boundaryfield,1,1,np_idx,1,1,0.0_DP,ERR,ERROR,*999)   
    CALL FIELD_PARAMETER_SET_UPDATE_NODE(boundaryfield,1,1,np_idx,2,1,0.0_DP,ERR,ERROR,*999)
    CALL FIELD_PARAMETER_SET_UPDATE_NODE(boundaryfield,1,1,np_idx,3,1,0.0_DP,ERR,ERROR,*999)  
    CALL FIELD_PARAMETER_SET_UPDATE_NODE(boundaryfield,1,1,np_idx,4,1,0.0_DP,ERR,ERROR,*999) 
    CALL FIELD_PARAMETER_SET_UPDATE_NODE(boundaryfield,1,1,np_idx,5,1,0.0_DP,ERR,ERROR,*999) 
    CALL FIELD_PARAMETER_SET_UPDATE_NODE(boundaryfield,1,1,np_idx,6,1,0.0_DP,ERR,ERROR,*999)           
  ENDDO  
!******

!******
  CALL FIELD_CREATE_START(5,region1,deffield,ERR,ERROR,*999)  
  CALL FIELD_TYPE_SET(5,region1,1,ERR,ERROR,*999)
  CALL FIELD_MESH_DECOMPOSITION_SET(deffield,decompositon,ERR,ERROR,*999)
  CALL FIELD_DEPENDENT_TYPE_SET(5,region1,2,ERR,ERROR,*999)
  CALL FIELD_GEOMETRIC_FIELD_SET(5,region1,undeffield,ERR,ERROR,*999)  
  CALL FIELD_CREATE_FINISH(region1,deffield,ERR,ERROR,*999)
  CALL FIELD_GEOMETRIC_PARAMETERS_UPDATE_FROM_INITIAL_MESH(deffield,ERR,ERROR,*999)
!  !CALL FIELD_PARAMETER_SET_COPY(deffield,1,5,ERR,ERROR,*999)
!******

  FILE="aaaa"
  METHOD="FORTRAN"
  CALL FIELD_IO_NODES_EXPORT(region1%FIELDS,FILE,METHOD,ERR,ERROR,*999)
!  CALL FIELD_IO_ELEMENTS_EXPORT(region1%FIELDS,FILE,METHOD,ERR,ERROR,*999)







 

  net=mesh1%TOPOLOGY(1)%PTR%ELEMENTS%NUMBER_OF_ELEMENTS
  DO ne_idx=1,net,1
    ne=mesh1%TOPOLOGY(1)%PTR%ELEMENTS%ELEMENTS(ne_idx)%GLOBAL_NUMBER
      
  ENDDO

  



  !FILE="aaaa"
  !METHOD="FORTRAN"
  !CALL FIELD_IO_NODES_EXPORT(region1%FIELDS,FILE,METHOD,ERR,ERROR,*999)

!************************************************************************************
  
  CALL CMISS_FINALISE(ERR,ERROR,*999)

  WRITE(*,'(A)') "Program successfully completed."
  
  STOP
999 CALL CMISS_WRITE_ERROR(ERR,ERROR)
  STOP
  
END PROGRAM FINITEELASTICITYEXAMPLE


